FORMAT: 1A
HOST: http://easymealorder.apiblueprint.org/

# easyMealOrder

easyMealOrder is a simple API allowing people to deal with meal order online.
The Documentation mode is https://easymealorder.docs.apiary.io

## Dishes Collection [/dishes]

### List All Dishes [GET]

+ Response 200 (application/json)

        [
            {
                "name": "白切鸡",
                "type": "food"
            },
            {
                "name": "可乐",
                "type": "drink"
            }
        ]
## Customer Collection [/orders]

### Customer submit order [POST]

You may post your order with an array like the one below

+ Request (application/json)

        [
            {
                "name": "白切鸡",
                "type": "food",
                "num" : 1,
                "note" : "不加辣"
            },
            {
                "name": "可乐",
                "type": "drink",
                "num" : 2,
                "note" : ""
            }
        ]

+ Response 201 (application/json)

    + Headers

            Location: /orders/1

    + Body

            {
                "id" : 1,
                "dishes" : ["白切鸡","可乐"],
                "time" : 10
            }

